### ISSUE TITLE
Add chipz to ultralisp

### ISSUE THREAD

**Issue by ghost** [sharplispers/chipz#5]
I'm not sure what the protocol is for something like this, could someone place this into ultralisp? 

If it is something I can do via a mirroring fork, then I'll do it. If a sharplisper member is empowered to do so then I request that it be so.

And if there is good reason to avoid it, I'm all ears. 

cheers

**Comment by xach** [comment]
Does the repo owner have to do it? If you want it in ultralisp, can you add it yourself? I don't know how ultralisp works in that regard.

**Comment by ghost** [comment]
I think I can fork chipz and include my fork.  My fork could just mirror the sharplispers fork. I wanted to ask before doing so however, so as not to step on anybody's toes. 

The ultralisp UI makes it pretty easy to "revoke" something that has been added (though, i'm not 100% sure that downstream consequences of such revocation have been well tested). 

I'm happy to try it though.

**Comment by ghost** [comment]
It seems I can just add the sharplispers version. 

https://ultralisp.org/projects/sharplispers/chipz 

sorry to trouble y'all.
